export { default as OwnerDashboard } from '../pages/vechicle_owners/dashboard/OwnerDashboard.tsx';
export { default as OwnerVerificationBanner } from '../components/owners_verification_banner.tsx';
export { default as OwnerSetupAccount } from '../pages/vechicle_owners/dashboard/owners_verification/OwnerSetupAccount.tsx';
export { default as OwnerAccountVerified } from '../pages/vechicle_owners/dashboard/owners_verification/owner_account_verified.tsx';
export { default as VehicleRegistration } from '../pages/vechicle_owners/dashboard/host_vehicles/VehicleRegistration.tsx';
export { default as OwnerWallet } from '../pages/vechicle_owners/dashboard/wallet/OwnerWallet.tsx';
export { default as OwnerWithdrawalForm } from '../pages/vechicle_owners/dashboard/wallet/OwnerWithdrawal.tsx';
export { default as Inspection } from '../pages/vechicle_owners/dashboard/inspection/Inspection.tsx';
export { default as InspectionBikeDetails } from '../pages/vechicle_owners/dashboard/inspection/InspectionBikeDetails.tsx';
export { default as OwnerReport } from '../pages/vechicle_owners/dashboard/report/OwnerReport.tsx';
export { default as ListedBikes } from '../pages/vechicle_owners/dashboard/listed_bikes/ListedBikes.tsx';
export { default as OwnerBikeDetails } from '../pages/vechicle_owners/dashboard/listed_bikes/OwnerBikeDetails.tsx';
export { default as OwnerProfileSettings } from '../pages/vechicle_owners/dashboard/profile/OwnerProfileSettings.tsx';

export { default as RiderDashboard } from '../pages/rider/dashboard/RiderDashboard.tsx';
export { default as RiderSetupAccount } from '../pages/rider/dashboard/rider_verification/RiderSetupAccount.tsx'
export { default as RiderVerificationBanner } from '../components/rider_verification_banner.tsx'
export { default as MotorcycleRental } from '../pages/rider/dashboard/rentals/MotorcycleRental.tsx';
export { default as MotorcycleDetails } from '../pages/rider/dashboard/rentals/MotorcycleDetails.tsx';
export { default as PendingMotorcycleDetails } from '../pages/rider/dashboard/rentals/PendingMotorcycleDetails.tsx';
export { default as BikeApplication } from '../pages/rider/dashboard/rentals/BikeApplication.tsx';
export { default as BikeApplicationFinale } from '../pages/rider/dashboard/rentals/bike_application_finale.tsx';
export { default as PaymentHistory } from '../pages/rider/dashboard/payment/PaymentHistory.tsx';
export { default as MakePayment } from '../pages/rider/dashboard/payment/MakePayment.tsx';
export { default as FleetManager } from '../pages/rider/dashboard/FleetManager.tsx';
export { default as RiderComplaints } from '../pages/rider/dashboard/complaints/RiderComplaints.tsx';
export { default as ComplaintForm } from '../pages/rider/dashboard/complaints/ComplaintForm.tsx';
export { default as BikeHistory } from '../pages/rider/dashboard/BikesHistory.tsx';
export { default as RiderProfileSettings } from '../pages/rider/dashboard/profile/RiderProfileSettings.tsx';
